alias tetris "vitetris"
alias install "sudo apt install"
alias remove "sudo apt remove"
alias purge "sudo apt purge"
alias minesweeper "freesweep"
alias home "cd ~"
alias documents "cd ~/Documents"
alias pictures "cd ~/Pictures"
alias videos "cd ~/Videos"
alias downloads "cd ~/Downloads"
alias music "cd ~/Music"
alias desktop "cd ~/Desktop"
alias starwars "telnet towel.blinkenlights.nl"
alias rofi "rofi -show run"
echo (set_color brgreen) "Cardboard Turtle's Fish Shell"
echo " "
neofetch
